-- Flink SQL 
-- 
-- smoke test
--
SELECT 
  -- TEST POINT CREATION & WKT CONVERSION
  ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_FUNCTIONS$ST_ASTEXT(
    ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(10.1601, 54.3362)
  ) AS KIEL_WKT,

  -- TEST DISTANCE CALCULATION (KIEL TO LABOE IS ~10KM / 5.4NM)
  ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_FUNCTIONS$ST_DISTANCESPHERE(
    ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(10.1601, 54.3362), 
    ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(10.2268, 54.3994)
  ) / 1852 AS TEST_DIST_NM
FROM (VALUES (1));

-- report every 5 minutes for all ships within 50 km of the Port of Kiel, you should use a Tumble Window 

SELECT 
    TUMBLE_START(eventTimestamp, INTERVAL '5' MINUTE) AS window_start,
    TUMBLE_END(eventTimestamp, INTERVAL '5' MINUTE) AS window_end,
    MMSI,
    -- Calculate distance in KM (meters / 1000)
    ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_FUNCTIONS$ST_DISTANCESPHERE(
        ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(Longitude, Latitude), 
        ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(10.1601, 54.3362)
    ) / 1000 AS dist_to_kiel_km
FROM `ssb`.`ssb_default`.`ais_events_record`
WHERE 
    -- Filter within 50 km (50,000 meters)
    ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_FUNCTIONS$ST_DISTANCESPHERE(
        ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(Longitude, Latitude), 
        ORG_APACHE_SEDONA_FLINK_EXPRESSIONS_CONSTRUCTORS$ST_POINT(10.1601, 54.3362)
    ) <= 50000
GROUP BY 
    TUMBLE(eventTimestamp, INTERVAL '5' MINUTE), 
    MMSI, 
    Latitude, 
    Longitude;
